name: Terraform Development Pipeline

on:
  push:
    branches:
      - dev

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

jobs:
  terraform-lint:
    name: Lint and Validate Terraform Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Format
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        run: terraform validate -recursive

      - name: Run tflint
        run: tflint

      - name: Run tfsec
        run: tfsec .

  terraform-deploy:
    name: Terraform Deploy to Development
    runs-on: ubuntu-latest
    needs: terraform-lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init -backend-config="key=dev.tfstate"

      - name: Terraform Plan
        run: terraform plan -var-file="deployments/terraform.tfvars.dev"

      - name: Terraform Apply
        run: terraform apply -input=false -auto-approve -var-file="deployments/terraform.tfvars.dev"
