name: Deploy Infrastructure to Development

on:
  push:
    branches:
      - 'dev'
    paths:
      - 'deployments/**'

jobs:
  terraform:
    runs-on: ubuntu-22.04
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      WORKING_DIR: ./deployments

    steps:
      - uses: actions/checkout@v4

      - name: Terraform init
        run: terraform init -backend-config="key=dev.tfstate"
        working-directory: ${{ env.WORKING_DIR }}

      - name: Terraform plan
        run: terraform plan -var-file="terraform.tfvars.dev"
        working-directory: ${{ env.WORKING_DIR }}

      - name: Terraform apply
        run: terraform apply -auto-approve -var-file="terraform.tfvars.dev"
        working-directory: ${{ env.WORKING_DIR }}
