name: Terraform Linter

on:
  pull_request:
    branches:
      - dev
      - staging
      - prod
  workflow_dispatch:

jobs:
  tflint:
    runs-on: ubuntu-22.04
    env:
      WORKING_DIR: ./deployments
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4.0.0

      - name: Run TFLint
        run: tflint
        working-directory: ${{ env.WORKING_DIR }}
