name: Terraform Security Check

on:
  pull_request:
    branches:
      - dev
      - staging
      - prod
  workflow_dispatch:

jobs:
  tfsec:
    runs-on: ubuntu-22.04
    env:
      WORKING_DIR: ./deployments
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          working_directory: ${{ env.WORKING_DIR }}
