name: Terraform Validation
on:
  push:
    branches-ignore:
      - 'main'
    paths:
      - ./**
jobs:
  terraform:
    name: 'Validate'
    runs-on: ubuntu-22.04

    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLEINT_SECRET: ${{ secret.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secret.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secret.AZURE_TENANT_ID }}
      WORKING_dir: ./deployments

    steps:
      - uses: actions/checkout@4.1.1

      - name: Terraform init
        id: init
        run: terraform init
        working-directory: ${{ env.WORKING_DIR }}
        
      - name: Terrafirn validate
        id: validate
        run: terraform validate
        working-directory: ${{ env.WORKING_DIR }}
