name: Terraform Validation

on:
  pull_request:
    branches:
      - dev
      - staging
      - prod

jobs:
  lint-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.9

      - name: Terraform Format Check
        run: terraform fmt -check -recursive
        working-directory: ./deployments

      - name: Terraform Init
        run: terraform init
        working-directory: ./deployments

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./deployments

      - name: Run TFLint
        run: tflint
        working-directory: ./deployments

      - name: Run tfsec
        run: tfsec .
        working-directory: ./deployments
